cart/ecommerceproject/cart/urls.py
from django.urls import path
from .import views
app_name='cart'
urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),

]

cart/ecommerceproject/ecommerceapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from ecommerceapp import views
app_name='ecommerceapp'
urlpatterns = [
   path('',views.allProdCat,name='allProdCat'),
   path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
   path('<slug:c_slug>/<slug:product_slug>/',views.ProdCatDetail,name='ProdCatDetail'),
]

cart/ecommerceproject/ecommerceproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from ecommerceapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',views.home,name='home'),
    path('ecommerceapp',include('ecommerceapp.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include("cart.urls")),
    path('Accounts/', include('Accounts.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/ecommerceproject/search_app/urls.py
from django.urls import path
from . import views


app_name='search_app'
urlpatterns = [

    path('',views.searchResult,name='searchResult'),
]

cart/ecommerceproject/cart/models.py
from django.db import models
from ecommerceapp.models import Product
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table='Cart'
        ordering=['date_added']

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price*self.quantity

    def __str__(self):
        return self.product

cart/ecommerceproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ecommerceapp.models import Product
from .models import CartItem,Cart
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart


def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id= _cart_id(request))
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total +=(cart_item.product.price * cart_item.quantity)
            counter +=cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,"cart.html",dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity>1:
        cart_item.quantity-=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

cart/ecommerceproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
     <link rel="stylesheet" href="{% static 'css/custom.css' %}" >
    <script src="http://kit.fontawesome.com/a076d05399.js"></script>
</head>
<body>
<div>
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}


</div>
    {% include 'footer2.html' %}
<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}" ></script>
<script src="{% static 'js/popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>
</body>
</html>

cart/ecommerceproject/templates/cart.html
{% extends 'base.html'  %}
{% load static %}
{% block metadescription %}

        welcome to the cart store where you can buy  items

{% endblock %}

{% block title %}
    cart-shop your favourites
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your Cart
        </h1>
        <br>
        <p class="text-center">
            please click <a href="{% url 'ecommerceapp:allProdCat' %}">Here</a>
        </p>
    </div>
</div>
{% else %}
<div>
<div class="text-center">
    <br>
    <h1 class="text-center my_title">
        Your Cart
    </h1>
    <br>
</div>
    </div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">Your Items</th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"><img src={{cart_item.product.image.url}} class="float-left rounded custom image" style="width:60px;height:60px;"></a>
                </td>
                <td class="text-left">
                    {{cart_item.product.name}}
                    <br>
                    SKU: {{cart_item.product.id}}
                    <br>
                    unit price:{{cart_item.product.price}}
                    QTY:{{cart_item.quantity}} x ₹ {{cart_item.product.price}}
                </td>
                <td>₹{{cart_item.sub_total}}</td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fas fa-cart-plus custom_icon"></i></a>&nbsp;
                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_icon"> <i class="fas fa-minus custom_icon"></i></a>&nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i></a>
                </td>
                {% else %}
                <td>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"> <i class="fas fa-minus custom_icon"></i></a>&nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th>
                    CheckOut
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    Please Review Your shopping Cart Items Before order
                </td>
            </tr>
            <tr>
            <td class="text-left">
                Your Total is <strong>₹{{ total }}</strong>
            </td>
            </tr>
            </tbody>
        </table>

    <div class="mx-auto">
        <a href="{% url 'ecommerceapp:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
        <a href="" class="btn btn-success btn-block my_custom_button">PAY ₹{{total}} AND PLACE ORDER</a>
    </div>
 </div>
</div><br>
{% endif %}
{% endblock %}

cart/ecommerceproject/templates/category.html
{% extends 'base.html'  %}
{% load static %}
{% block metadescription %}
{% if category %}
{{ category.desc |truncatewords:155 }}
{% else %}
welcome to the cart store where you can buy  items
{% endif %}

{% endblock %}

{% block title %}
{% if category %}
{{ category.name }}--shop cart
{% else %}
see our collections--shop cart
{% endif %}
{% endblock %}

{% block content %}
{% if category %}
<div class="row my_row_class">
    <div class="mx-auto">
        <p><a href="{% url 'ecommerceapp:allProdCat' %}">YOUR GROCERY STORE </a>{{ category.name }}</p>
    </div>
</div>
{% endif %}
<div class="mx-auto">
    {% if category %}
   <center><img class="my_image" src="{{ category.image.url }}" alt="{{ category.name}}" style="height:300px;width:1000px;"></center> 
</div><br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify text-center">{{category.desc}}</p>
</div>
{% else %}
<div>
    <center><img class="my_image my_image_padding" src=" media/img/banner3.png " style="width:1260px;height:300px;" alt=""></center>
</div>io
<br>
<div>
    <h1 style="color:blue" class="text-center my_title"><b>GroCart</b></h1>
    <p class="text-center"><b>YOUR GROCERY STORE</b></p>
</div>
{% endif %}
<div class="container">
    <div class="row max-auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="min-width: 18rem;">
                <a href="{{product.get_url}}"><img class="card" src="{{product.image.url}}" alt="{{product.name}}"
                                                   style="height:330px;width:349px"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <h4>₹{{product.price}}</h4>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} activate {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
    </div>
</div>

    {% include 'footer.html' %}
{% endblock %}

cart/ecommerceproject/templates/footer.html
<!-- Footer -->
<footer class=" text-center text-lg-start" style="background-color: rgba(0,0,0,1) ">
    <!-- Grid container -->
    <div class="container p-4">
        <!--Grid row-->
        <div class="row">
            <!--Grid column-->
            <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
                <h5 class="text-uppercase" style="color:grey;">GroCart</h5>

                <p style="color:grey;">
                    We deliver to 25 cities across India and maintain excellent delivery times, ensuring that all your
                    products from groceries to snacks branded foods reach you in time.Express Delivery: This super
                    useful service can be availed by customers in cities like Bangalore, Mumbai, Pune, Chennai, Kolkata,
                    Hyderabad and Delhi-NCR in which we deliver your orders to your doorstep in 90 Minutes.
                </p>
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                <ul class="list-unstyled mb-0">
                        {% for cat in links %}
                    <li><a href="{{ cat.get_url }}" style="color:grey;">{{ cat.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                <ul class="list-unstyled">
                    <li>
                        <a href="Accounts/login" style="color:grey;">LOGIN</a><br>
                        <hr>
                        <a href="Accounts/register" style="color:grey;">SIGN UP </a>
                    </li>
                </ul>
            </div>
            <!--Grid column-->
        </div>
        <!--Grid row-->
    </div>
    <!-- Grid container -->
</footer>
<!-- Footer -->

cart/ecommerceproject/templates/footer2.html
<div class="footer navbar-fixed-bottom my_footer">
  <center><p  style="background-color: rgba(0, 0, 0, 0.9);color:grey;" class="text-center" >&copy; GroCart. All Rights Reserved</p></center>
</div>

cart/ecommerceproject/templates/header.html
<!--{% load static %}-->
<!--<div>-->
<!--    <center>-->
<!--        <img src="{% static 'img/logo.png' %}" alt='it is a logo'>-->
<!--    </center>-->
<!--</div>-->

cart/ecommerceproject/templates/home.html
  &nbsp;<li><a class="btn btn-warning"  href="Accounts/login" > Sign In </a></li>

cart/ecommerceproject/templates/login.html
{% extends 'base.html'  %}
{% load static %}
{% block metadescription %}

        welcome to the Grocart

{% endblock %}

{% block title %}
    SIGN IN AND EXPLORE
{% endblock %}
{% block content %}

<form class="text-center" action="login" method="post">
    {% csrf_token %}
    <hr>
    <hr>
    <input type="text" name="username" placeholder="username"><br>
    <input type="password" name="password" placeholder="password"><br>
    <input type="submit" value="login"><br>

</form>
{% endblock %}

cart/ecommerceproject/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<!--      <a class="navbar-brand" href="#" img src="media/img/logo.png'" alt='it is a logo'></a>-->
    <img src="{% static 'img/logo3.png' %}" alt='it is a logo'>
    {%if user.is_authenticated %}
    <li style="color:white">Welcome {{user.username}}</li>
    <li><a class="btn btn-primary"  href="Accounts/logout" style="color:white">Logout</a></li>
    {% else %}
    &nbsp;<li><a class="btn btn-success " href="Accounts/register" >Sign Up</a></li>
    &nbsp;<li><a class="btn btn-warning"  href="Accounts/login" > Sign In </a></li>
    {% endif %}
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
<!--            <li class="nav-item active">-->
<!--                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>-->
<!--            </li>-->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <h7 style="color:white">View Category</h7>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'ecommerceapp:allProdCat' %}">All Products</a>
                    {% for cat in links %}
                    <a class="dropdown-item" href="{{ cat.get_url }}">{{ cat.name }}</a>
                    {% endfor %}
                    <!--          <div class="dropdown-divider"></div>-->
                    <!--          <a class="dropdown-item" href="#">Something else here</a>-->
                    <!--        </div>-->
            </li>
            {% if item_count > 0 %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fas fa-cart-plus"> {{item_count}}</i></a>
            </li>
            {% endif %}
            <!--      <li class="nav-item">-->
            <!--        <a class="nav-link disabled" href="#">Disabled</a>-->
            <!--      </li>-->
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:searchResult' %}" method="get">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
        </form>
    </div>
</nav>

<!--<nav>-->
<!--    <ul>-->
<!--        <li><a href="{% url 'ecommerceapp:allProdCat' %}">ALL PRODUCTS</a> </li>-->
<!--        {% for cat in links %}-->
<!--            <li><a href="{{ cat.get_url }}">{{ cat.name }}</a> </li>-->

<!--        {% endfor %}-->
<!--     <li>your cart</li>-->
<!--    </ul>-->


<!--</nav><br>-->

cart/ecommerceproject/templates/product.html
{% extends 'base.html'  %}
{% load static %}
{% block metadescription %}
{{ product.desc |truncatewords:155 }}
{% endblock %}
{% block title %}
{{ product.name }}--shop cart
{% endblock %}
{% block content %}
<div class="row my_product_row_class">
    <div class="mx-auto">
        <p><a href="{% url 'ecommerceapp:allProdCat' %}">HOME</a>|<a href="{{product.category.get_url}}"></a>{{product.name}}
        </p>
    </div>
    <div class="container">
        <br>
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <div style="min-width:18rem;">
                    <img src="{{product.image.url}}" alt="{{product.name}}"
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
                <h1 class="my_prod_title">{{product.name}}</h1>
                <p>₹{{product.price}}</p>
                <p class="my_title">Product Description</p>
                <p class="text-justify my_prod_text">{{product.desc}}</p>
                {% if product.stock <= 0 %}
                <p class="text-justify my_prod_text"><b>OUT OF STOCK</b></p>
                {% else %}
                <a class="btn btn-secondary " href="{% url 'cart:add_cart' product.id %}">ADD TO CART</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

cart/ecommerceproject/templates/registration.html
{% extends 'base.html'  %}
{% load static %}
{% block metadescription %}

        welcome to the Grocart

{% endblock %}

{% block title %}
    SIGN IN AND EXPLORE
{% endblock %}
{% block content %}

<form class="text-center" action="register" method="post">
    {% csrf_token %}
    <hr>
    <hr>
    <input type="text" name="username" placeholder="username"><br>

    <input type="text" name="first_name" placeholder="first_name"><br>

    <input type="text" name="last_name" placeholder="last_name"><br>

    <input type="email" name="email" placeholder="email"><br>

    <input type="password" name="password1" placeholder="password"><br>

    <input type="password" name="password2" placeholder="password"><br>

    <input type="submit" value="registration"><br>


</form>
<div>
   {% for message in messages %}
    <h4>{{message}}</h4>
    {% endfor %}
</div>
{% endblock %}

cart/ecommerceproject/templates/search.html
{% extends 'base.html'  %}
{% load static %}
{% block metadescription %}
    {{ product.desc |truncatewords:155 }}
{% endblock %}
{% block title %}
    {{ product.name }}--shop cart
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for: {{query}}</p>
</div>

<div class="container">
    <div class="row max-auto">
        {% for product in products %}
         <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
        <div class="card text-center" style="min-width: 18rem;">
                <a href="{{product.get_url}}"><img class="card" src="{{product.image.url}}" alt="{{product.name}}" style="height:330px;width:349px"></a>
                <div class="card-body">
                   <h4 >{{product.name}}</h4>
                    <h4>₹{{product.price}}</h4>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="mx-auto">
            <p class="text-center my_search_text">No Results found</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}